### PR TITLE
Add wedge agent

### PR DESCRIPTION
**Pull request by david-lopez-glez**
Added 3 workflows of Wedge Agent
Removed one workflow gone from the EVP Device Agent as it is now part of the wedge agent

### CODE REVIEW

**Comment by jordi-midokura** [comment]
IMO, there are information redundant
Serveral workflows are executed inside main.yml, so we can group them
image

Also, I don'¡t understand the "no status" on build agent. The workflow seems well linked

**Comment by david-lopez-glez** [comment]
> IMO, there are information redundant Serveral workflows are executed inside main.yml, so we can group them image
> 
> Also, I don'¡t understand the "no status" on build agent. The workflow seems well linked

I'll squash them in the next PR, this is about adding the wedge agent

**Review by midokura-xavi92 — APPROVED** [review]
LGTM already, but @jordi-midokura 's [suggestions](https://github.com/midokura/evp-overview/pull/11#issuecomment-1539976967) might require additional changes.

**Comment by david-lopez-glez** [comment]
> LGTM already, but @jordi-midokura 's [suggestions](https://github.com/midokura/evp-overview/pull/11#issuecomment-1539976967) might require additional changes.

Yes, as mentioned here:https://github.com/midokura/evp-overview/pull/11#issuecomment-1545446793 I will do it in the next PR

**Review by jordi-midokura — APPROVED** [review]

**Comment by jordi-midokura** [comment]
> > IMO, there are information redundant Serveral workflows are executed inside main.yml, so we can group them image
> > Also, I don'¡t understand the "no status" on build agent. The workflow seems well linked
> 
> I'll squash them in the next PR, this is about adding the wedge agent

ok, in another PR. 
i didn't see that it was only adding wedge-agent

**Pull request merged**
